# This is a basic workflow to help you get started with Actions

name: Arduino Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - fqbn: "esp8266:esp8266:generic"
            platform-name: esp8266:esp8266
          - fqbn: "esp32:esp32:esp32wrover"
            platform-name: esp32:esp32
        include:
          - board:
              platform-name: esp8266:esp8266
            platforms: |
              # Install ESP8266 platform via Boards Manager
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
                version: 3.1.1
              # Install ESP32 platform via Boards Manager
              - name: esp32:esp32
                source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
                version: 3.0.7
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1
        with:
              platforms: ${{ matrix.platforms }}
              fqbn: ${{ matrix.board.fqbn }}
              libraries: |
                - source-url: "https://github.com/FastLED/FastLED.git"
                  name: FastLED
                - source-url: "https://github.com/Links2004/arduinoWebSockets.git"
                  name: WebSockets
                - source-url: "https://github.com/BorisKofman/IRremoteESP8266.git"
                  version: "Espressif-version-3"
                  name: IRremoteESP8266
                - source-url: "https://github.com/tzapu/WiFiManager.git"
                  name: WiFiManager
                - source-url: "https://github.com/hideakitai/DebugLog.git"
                  name: DebugLog
                - source-url: "https://github.com/hideakitai/ArxTypeTraits.git"
                  name: ArxTypeTraits
                - source-url: "https://github.com/hideakitai/ArxContainer.git"
                  name: ArxContainer
              sketch-paths: |
                - ./
